"""
Retail Demand Forecasting — Streamlit App
==========================================

Reads the artifacts produced at the end of the notebook:
  - demand_forecast_28days_<N>products.csv   (future predictions)
  - sales_history_90days_<N>products.csv     (recent actuals)

Two ways to use it:
  1. Explore & Predict  — pick a state / store / product, choose a horizon,
     hit "Predict" and get the actual-vs-forecast chart, KPIs, and a
     day-by-day table.
  2. Bulk Upload Predict — upload a CSV/Excel file with a list of item IDs,
     hit "Predict", and get a compact summary table with each item's
     forecasted demand for the chosen horizon.

Run with:
    streamlit run streamlit_app.py
"""

import difflib
import glob
import json
import os

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

# --------------------------------------------------------------------------
# Page setup
# --------------------------------------------------------------------------
st.set_page_config(
    page_title="Retail Demand Forecasting",
    page_icon="📈",
    layout="wide",
)

st.markdown(
    """
    <style>
    div[data-testid="stMetric"] {
        background-color: rgba(31, 119, 180, 0.06);
        border: 1px solid rgba(31, 119, 180, 0.15);
        border-radius: 10px;
        padding: 12px 14px;
    }
    div[data-testid="stMetricLabel"] { font-weight: 600; }
    .block-container { padding-top: 2rem; }
    </style>
    """,
    unsafe_allow_html=True,
)

FORECAST_PATTERN = "demand_forecast_28days_*products.csv"
HISTORY_PATTERN = "sales_history_90days_*products.csv"
METADATA_PATTERN = "run_metadata_*products.json"
MAX_HORIZON = 28
REQUIRED_FORECAST_COLS = {"item_id", "store_id", "state_id", "date", "predicted_sales"}
REQUIRED_HISTORY_COLS = {"item_id", "store_id", "state_id", "date", "sales"}


# --------------------------------------------------------------------------
# Data loading
# --------------------------------------------------------------------------
def _latest_file(pattern: str):
    """Return the most recently modified file matching `pattern`, or None."""
    matches = glob.glob(pattern)
    if not matches:
        return None
    return max(matches, key=os.path.getmtime)


@st.cache_data(show_spinner="Loading forecast and history data...")
def load_data():
    forecast_path = _latest_file(FORECAST_PATTERN)
    history_path = _latest_file(HISTORY_PATTERN)

    if forecast_path is None or history_path is None:
        return None, None, forecast_path, history_path

    forecast_df = pd.read_csv(forecast_path, parse_dates=["date"])
    history_df = pd.read_csv(history_path, parse_dates=["date"])
    return forecast_df, history_df, forecast_path, history_path


@st.cache_data(show_spinner=False)
def load_run_metadata():
    """Best-effort load of the notebook's run_metadata_*.json, if present."""
    metadata_path = _latest_file(METADATA_PATTERN)
    if metadata_path is None:
        return None
    try:
        with open(metadata_path) as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return None


# Sidebar "reload" button needs to clear the cache before we load anything below.
if st.sidebar.button("🔄 Reload data files"):
    st.cache_data.clear()
    st.rerun()

forecast_df, history_df, forecast_path, history_path = load_data()
run_metadata = load_run_metadata()

# --------------------------------------------------------------------------
# Guard: missing artifacts
# --------------------------------------------------------------------------
if forecast_df is None or history_df is None:
    st.title("📈 Retail Demand Forecasting")
    st.error(
        "Couldn't find the notebook's output files in this folder.\n\n"
        f"Expected something matching **`{FORECAST_PATTERN}`** and "
        f"**`{HISTORY_PATTERN}`**.\n\n"
        "Run the notebook through Section 8 first, then place this app in "
        "the same folder as the generated `.csv` files (or copy the CSVs "
        "here)."
    )
    st.stop()

# Guard: files found, but not in the shape the app expects
missing_forecast_cols = REQUIRED_FORECAST_COLS - set(forecast_df.columns)
missing_history_cols = REQUIRED_HISTORY_COLS - set(history_df.columns)
if missing_forecast_cols or missing_history_cols:
    st.title("📈 Retail Demand Forecasting")
    st.error(
        "The forecast/history files were found but don't have the expected columns.\n\n"
        f"Missing in forecast file: {missing_forecast_cols or 'none'}\n\n"
        f"Missing in history file: {missing_history_cols or 'none'}\n\n"
        "Make sure these were generated by the current version of the notebook."
    )
    st.stop()

ALL_ITEM_IDS = sorted(forecast_df["item_id"].unique())

# --------------------------------------------------------------------------
# Sidebar — global settings + data source info
# --------------------------------------------------------------------------
st.sidebar.title("⚙️ Settings")
st.sidebar.caption(
    f"Forecast file: `{os.path.basename(forecast_path)}`  \n"
    f"History file: `{os.path.basename(history_path)}`"
)

horizon = st.sidebar.slider(
    "Forecast horizon (days ahead)",
    min_value=1,
    max_value=MAX_HORIZON,
    value=MAX_HORIZON,
    help="How many of the next days to include in charts, KPIs, and tables.",
)

st.sidebar.markdown("---")
st.sidebar.metric("Products available", f"{len(ALL_ITEM_IDS):,}")
st.sidebar.metric(
    "Categories covered",
    f"{history_df['item_id'].str.extract(r'^([A-Z]+)')[0].nunique()}",
)

if run_metadata:
    st.sidebar.markdown("---")
    metrics = run_metadata.get("metrics", {})
    st.sidebar.caption(
        f"Model in use: **{run_metadata.get('best_model', 'unknown')}**  \n"
        + (
            f"RMSE: {metrics['rmse']:.3f} | MAPE: {metrics['mape']:.1f}%"
            if {"rmse", "mape"} <= metrics.keys()
            else ""
        )
    )

st.title("📈 Retail Demand Forecasting")

tab_explore, tab_bulk = st.tabs(["🔍 Explore & Predict", "📁 Bulk Upload Predict"])

# ==========================================================================
# TAB 1 — Explore & Predict (single product, interactive)
# ==========================================================================
with tab_explore:
    st.caption(
        "Pick a state, store, and product below, then click **Predict** to "
        "generate the forecast."
    )

    col_a, col_b, col_c = st.columns(3)
    with col_a:
        states = sorted(history_df["state_id"].unique())
        selected_state = st.selectbox("State", states, key="state_select")
    with col_b:
        stores_in_state = sorted(
            history_df.loc[history_df["state_id"] == selected_state, "store_id"].unique()
        )
        selected_store = st.selectbox("Store", stores_in_state, key="store_select")
    with col_c:
        products_in_store = sorted(
            history_df.loc[
                (history_df["state_id"] == selected_state)
                & (history_df["store_id"] == selected_store),
                "item_id",
            ].unique()
        )
        selected_product = st.selectbox("Product", products_in_store, key="product_select")

    predict_clicked = st.button("🔮 Predict", type="primary", use_container_width=False)

    # Remember the last prediction so the result stays visible across reruns
    # (e.g. when the horizon slider in the sidebar changes) without forcing
    # the user to click Predict again for the same selection.
    if predict_clicked:
        st.session_state["last_selection"] = (selected_state, selected_store, selected_product)

    if "last_selection" in st.session_state:
        sel_state, sel_store, sel_product = st.session_state["last_selection"]

        hist_series = history_df[
            (history_df["item_id"] == sel_product) & (history_df["store_id"] == sel_store)
        ].sort_values("date")

        fcst_series = (
            forecast_df[
                (forecast_df["item_id"] == sel_product) & (forecast_df["store_id"] == sel_store)
            ]
            .sort_values("date")
            .head(horizon)
        )

        if hist_series.empty or fcst_series.empty:
            st.warning("No data found for this exact product/store combination.")
        else:
            st.markdown(f"### Results — **{sel_product}** @ **{sel_store}** ({sel_state})")

            avg_last_28_actual = hist_series["sales"].tail(28).mean()
            avg_forecast = fcst_series["predicted_sales"].mean()
            pct_change = (
                (avg_forecast - avg_last_28_actual) / avg_last_28_actual * 100
                if avg_last_28_actual > 0
                else 0.0
            )
            total_forecast_units = fcst_series["predicted_sales"].sum()

            col1, col2, col3 = st.columns(3)
            col1.metric("Avg. daily sales — last 28 days", f"{avg_last_28_actual:.1f} units")
            col2.metric(
                f"Avg. daily forecast — next {horizon} days",
                f"{avg_forecast:.1f} units",
                delta=f"{pct_change:+.1f}%",
            )
            col3.metric(f"Total forecast — next {horizon} days", f"{total_forecast_units:,.0f} units")

            # --- Combined actual + forecast chart ---
            fig = go.Figure()
            fig.add_trace(
                go.Scatter(
                    x=hist_series["date"], y=hist_series["sales"],
                    mode="lines", name="Actual sales",
                    line=dict(color="#1f77b4", width=2),
                )
            )
            fig.add_trace(
                go.Scatter(
                    x=fcst_series["date"], y=fcst_series["predicted_sales"],
                    mode="lines+markers", name=f"Forecast (next {horizon} days)",
                    line=dict(color="#ff7f0e", width=2, dash="dash"),
                    marker=dict(size=5),
                )
            )
            boundary_date = hist_series["date"].max()
            fig.add_vline(
                x=boundary_date.timestamp() * 1000,
                line_width=1, line_dash="dot", line_color="gray",
            )
            fig.update_layout(
                template="plotly_white",
                xaxis_title="Date", yaxis_title="Units sold",
                legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
                hovermode="x unified", height=460,
                margin=dict(l=10, r=10, t=30, b=10),
            )
            st.plotly_chart(fig, use_container_width=True)

            # --- Day-by-day forecast table (exactly the requested horizon) ---
            st.markdown(f"**Day-by-day forecast — next {horizon} days**")
            daily_table = fcst_series[["date", "predicted_sales"]].rename(
                columns={"date": "Date", "predicted_sales": "Forecasted Units"}
            )
            daily_table["Date"] = daily_table["Date"].dt.strftime("%Y-%m-%d")
            st.dataframe(daily_table.reset_index(drop=True), use_container_width=True, height=280)

            st.download_button(
                "⬇️ Download this forecast as CSV",
                data=daily_table.to_csv(index=False).encode("utf-8"),
                file_name=f"{sel_product}_{sel_store}_forecast_{horizon}days.csv",
                mime="text/csv",
                key="single_forecast_download",
            )

            with st.expander("Show recent actuals (last 90 days)"):
                st.dataframe(hist_series.reset_index(drop=True), use_container_width=True)
    else:
        st.info("Select a state, store, and product above, then click **Predict**.")

# ==========================================================================
# TAB 2 — Bulk Upload Predict (many products at once)
# ==========================================================================
with tab_bulk:
    st.caption(
        "Upload a CSV or Excel file containing a column of product IDs "
        "(e.g. `item_id`, `item`, `product`, or `sku`) — one per row — "
        "then click **Predict** to get each item's forecasted demand."
    )

    uploaded_file = st.file_uploader(
        "Upload item list", type=["csv", "xlsx", "xls", "txt"], key="bulk_upload"
    )

    with st.expander("ℹ️ File format example"):
        st.code("item_id\nFOODS_3_090\nHOUSEHOLD_1_118\nHOBBIES_2_005", language="text")

    if uploaded_file is not None:
        raw_upload = None
        try:
            if uploaded_file.name.lower().endswith((".xlsx", ".xls")):
                raw_upload = pd.read_excel(uploaded_file)
            else:
                raw_upload = pd.read_csv(uploaded_file)
        except Exception as exc:
            st.error(f"Couldn't read that file: {exc}")

        if raw_upload is not None:
            st.dataframe(raw_upload.head(3), use_container_width=True)

            # Detect which column holds the item IDs; fall back to letting
            # the user pick manually rather than silently guessing wrong.
            candidate_cols = [
                c for c in raw_upload.columns
                if c.strip().lower() in {"item_id", "item", "product", "product_id", "sku"}
            ]
            if candidate_cols:
                id_col = candidate_cols[0]
            else:
                id_col = st.selectbox(
                    "Couldn't auto-detect the ID column — pick it manually:",
                    raw_upload.columns.tolist(),
                    key="bulk_id_col_select",
                )

            requested_items = (
                raw_upload[id_col]
                .astype(str)
                .str.strip()
                .replace("", pd.NA)
                .dropna()
                .unique()
                .tolist()
            )

            st.write(f"Detected **{len(requested_items)}** item ID(s) in column `{id_col}`.")

            predict_bulk_clicked = st.button(
                "🔮 Predict for uploaded items", type="primary", key="bulk_predict_btn"
            )

            if predict_bulk_clicked:
                st.session_state["bulk_items"] = requested_items

    if "bulk_items" in st.session_state:
        requested_items = st.session_state["bulk_items"]

        rows = []
        unmatched = []
        for raw_item in requested_items:
            # Exact match first, case-insensitive fallback
            match = raw_item if raw_item in ALL_ITEM_IDS else None
            if match is None:
                ci_matches = [i for i in ALL_ITEM_IDS if i.lower() == raw_item.lower()]
                match = ci_matches[0] if ci_matches else None

            if match is None:
                unmatched.append(raw_item)
                continue

            item_rows = forecast_df[forecast_df["item_id"] == match].sort_values("date")
            n_stores = item_rows["store_id"].nunique()
            total_units = (
                item_rows.groupby("store_id")
                .apply(lambda g: g.head(horizon)["predicted_sales"].sum())
                .sum()
            )

            rows.append(
                {
                    "Item ID": match,
                    "Stores selling it": n_stores,
                    f"Forecasted units (next {horizon}d, all stores)": round(float(total_units), 1),
                    "Avg. per store per day": round(float(total_units) / max(n_stores, 1) / horizon, 2),
                }
            )

        if rows:
            st.markdown(f"### Forecast summary — next {horizon} days")
            result_table = pd.DataFrame(rows).sort_values(
                f"Forecasted units (next {horizon}d, all stores)", ascending=False
            )
            st.dataframe(result_table.reset_index(drop=True), use_container_width=True)

            # Small comparison chart across the uploaded items
            bar_fig = go.Figure(
                go.Bar(
                    x=result_table["Item ID"],
                    y=result_table[f"Forecasted units (next {horizon}d, all stores)"],
                    marker_color="#1f77b4",
                )
            )
            bar_fig.update_layout(
                template="plotly_white",
                xaxis_title="Item", yaxis_title=f"Forecasted units (next {horizon}d)",
                height=360, margin=dict(l=10, r=10, t=20, b=10),
            )
            st.plotly_chart(bar_fig, use_container_width=True)

            st.download_button(
                "⬇️ Download results as CSV",
                data=result_table.to_csv(index=False).encode("utf-8"),
                file_name=f"bulk_forecast_{horizon}days.csv",
                mime="text/csv",
            )

        if unmatched:
            st.warning(
                f"{len(unmatched)} item(s) not found in this dataset "
                f"(only the top {len(ALL_ITEM_IDS):,} selected products are available):"
            )
            for bad_item in unmatched:
                suggestions = difflib.get_close_matches(bad_item, ALL_ITEM_IDS, n=3, cutoff=0.5)
                if suggestions:
                    st.write(f"- `{bad_item}` — did you mean: {', '.join(f'`{s}`' for s in suggestions)}?")
                else:
                    st.write(f"- `{bad_item}` — no close match found")

st.markdown("---")
st.caption(
    "Forecasts are generated with a recursive 28-day walk-forward using the "
    "best model selected in the notebook (XGBoost or LightGBM, chosen by RMSE). "
    "The horizon slider in the sidebar trims the pre-computed 28-day forecast; "
    "it doesn't re-run the model live."
)